### ISSUE TITLE
GW's arm9loaderhax.bin support on the chainloader for no-screeninit users.

### ISSUE THREAD

**Issue by billy-acuna** [LumaTeam/Luma3DS#113]
Looks like GW's payload or launcher.dat (dunno at all) doesn't like no-screeninit A9LH setup.
Is this fixable by including screeninit code to "(botton)_GW.bin" entry on "payloads" folder?

**Comment by urherenow** [comment]
Luma3DS has nothing to do with this, and GW's stuff is not open source, so there's no changing it. Change/Update your a9lh.

**Comment by Hartie95** [comment]
You could use another bootloader, with screen init.

Also it should not be the problem that gw is closed source, since its a simple a9lh payload.

**Comment by urherenow** [comment]
Simple? If you say so. Their loader.dat was only ever partially reversed because it's obfuscated like crazy. Just enough for CFW to be born. Still, many of their methods haven't been reversed, such as their cheat engine and how it hooks pretty much everything that runs on native_firm.Heck even getting different language DLC running didn't happen until recently.

If you can inject screen init to their code, please do, but there's nothing wrong with my answer.

**Comment by Hartie95** [comment]
We are talking about GW's arm9loaderhax.bin, which simply loads their launcher.dat, not from directly loading their launcher.dat. So it doesn't have to do something with closed source or open source, its only a simple arm9loaderhax payload from GW.

**Comment by billy-acuna** [comment]
Of course it doesn't have to do something with closed/open source, the payload just loads launchet.dat, but the fact is that launcher.dat (or perhaps GW's payload?) doesn't like no-screeninit or "dark" screeninit, it starts only with full-bright screeninit.That's why only boots with bootctr9 for no-screeninit users.

**Comment by urherenow** [comment]
Jesus, you people are dense. Open source matters because you can't inject the screen init code via hex editing GW's .bin. Your issue is that you're too lazy to take the 2 minutes to install a screen init version of a9lh. This is not a Luma3DS issue at all and should be closed. I'm not sure if the Luma config.bin is looked at before chainloading or not, but have you tried enabling splash on no screen init version and set brightness to the max?

**Comment by TuxSH** [comment]
>  I'm not sure if the Luma config.bin is looked at before chainloading or not

It's looked at [very early](https://github.com/AuroraWright/Luma3DS/blob/master/source/firm.c#L47) indeed.

**Comment by urherenow** [comment]
Lines 147-150. Chain loading is done right before splash screen stuff is fished out of the config. But does the action of calling the config trigger screen init code...? My first guess is no, because it's just a file read.

Edit: after bothering to read through some of the code, it's actually trivial to do a screen init at any time, really. Even before chain loading anything. At my skill level, I couldn't make it general, but rather assign screen init to a specific button press. For example, holding "down" would screen init followed by launching the down_whatever.bin.

**Comment by AuroraWright** [comment]
What are you all saying? Luma does screen init before launching a payload... any payload
