### ISSUE TITLE
exceptional error has occured Arm11 (Core 1) 

### ISSUE THREAD

**Issue by JayVagabond** [LumaTeam/Luma3DS#1187]
I did my old 3DS has the latest 11.8.0-41E & I have just installed safeb9 w/ all the boot9strap 1.3 files via guide through recovery mode then of course the latest version of Luma3DS 9.1 via also the guide. After I enabled hb app via rosalina menu on download play I attempt to lauch the homebrew on download play and it gives me the arm11 (core1) error, Same also w/ the steelhax I was using before I installed B9S 1.3 and Luma3DS 9.1. Please help me out. Thank you. Dump files are attached for reference.

[Dumps.zip](https://github.com/AuroraWright/Luma3DS/files/2420977/Dumps.zip)

**Comment by Jimi-GG** [comment]
Hi,
I had the same issue as you when trying to launch the homebrew on download play. My arm11 (core1) error was due to a file incorrectly spelled. I fixed the issue by renaming the file "boot(1).3dsx" to "boot.3dsx" on the root of my SD card. I suggest you to check the name of all the files/folders on your SD card and make sure everything is correct. Hope it helps

**Comment by Margen67** [comment]
@yuukieve I believe you've mislabeled the issue. It's an _exceptional_ error :^)
