### ISSUE TITLE
what's mean momiji？

### ISSUE THREAD

**Issue by Matthewliu7** [LumaTeam/Luma3DS#1197]
When I play pokemon，it always broken with momiji in luma error list.
I can't fix it,even ctrtransfer....
How can I fix it?

**Comment by jonirrings** [comment]
if it is an in-game item, it the game issue, not Luma3DS. [momiji](https://en.wikipedia.org/wiki/Momiji_(disambiguation))
if not an in-game item, a screenshot may be expected.

**Comment by Vikijaka** [comment]
Same here Pokémon UM+o3DS, since update to Luma9.1 i got this "momiji" Error, when i am leaving/porting at my current Area (Team Magma@AetherFoundation). its possible to go through all Rooms, but i can't leave it via Entrance nor after Groudon fight via Teleporter.

![img_20181024_151639](https://user-images.githubusercontent.com/29962702/47433108-009f9e00-d7a0-11e8-82ed-6b894c84c5eb.jpg)

EDIT:
If i dump PMUM+SAVE, i can play it on citra nightly129ca89 just fine. My SD Card's (testet multiple) are also fine

**Comment by noirscape** [comment]
Momiji is just the name of the process that Pokemon has.

Are any of you using no-outline patches or anything?

**Comment by Matthewliu7** [comment]
> Momiji is just the name of the process that Pokemon has.
> 
> Are any of you using no-outline patches or anything?

How can I fix the problem？I was try ctrtansfer and get other ROM，but it useless..

No-outline before 1.1update is useful.

**Comment by noirscape** [comment]
@Matthewliu7 - Are you using any patches for Pokemon.

If you don't know what that means, post an image of the `luma/titles` folder from your SD card here.

**Comment by Matthewliu7** [comment]
Of course No patch,I just told he no-outline patch is useless...I don't use the patch...

**Comment by ghost** [comment]
Can't reprieve reproduce, but these crashes can be caused by bad installs, corrupt save data, etc. Not a Luma issue.
