### ISSUE TITLE
Luma 9.2?

### ISSUE THREAD

**Issue by MasterGamingYT** [LumaTeam/Luma3DS#1224]
I'm just asking when is Luma 9.2 is coming out

**Comment by Conan179** [comment]
When it is finished :)

**Comment by 823403553** [comment]
Correct



在 2019年3月4日，上午4:27，Conan179 <notifications@github.com<mailto:notifications@github.com>> 写道：


When it is finished :)

**Comment by Shadow322** [comment]
why do u think u need a v9.2?

**Comment by Nemris** [comment]
@Shadow322 They might be hinting at the long list of suggestions at #752, plus the 19 commits since 9.1.

**Comment by Shadow322** [comment]
@DMSalesman 13 commits and its not like they cant get off ther ass to compile a copy themselfs

**Comment by Nemris** [comment]
@Shadow322 I know. I myself compiled a copy, but had to roll back due to a nasty sleep mode bug I'm not able to debug.

**Comment by Multimegamander** [comment]
Seeing as there's a site that compiles Luma every commit, there's no reason to complain about a new release, and you can use MultiUpdater with a custom .JSON to update to each commit on the 3DS itself

**Comment by RS55** [comment]
Lack of activity occurred coincidentally when deciding to do gender reassignment surgery... so nobody will know when he will return.

That or someone makes an active fork in that time and takes the list of suggestions and improvements that have been asking for a long while lol because even the cheats need improvements

**Comment by AuroraWright** [comment]
Lack of activity occurred coincidentally also with other personal and mental health-related issues associated with a decreased interest in console hacking in general. The fact that there's not a net positive return for my work due to disrespectful and/or hateful users (like you) doesn't contribute positively either ¯\\\_(ツ)\_/¯

That said, @ OP no ETAs.

**Comment by TuxSH** [comment]
I'm doing some work on luma3ds, I've been doing switch stuff/being busy otherwise. As you can see there's  activity on the repo.
