### ISSUE TITLE
just making sure

### ISSUE THREAD

**Issue by Reual4412** [LumaTeam/Luma3DS#129]
does this work on 11.0.0-33u without any problems or you know bricks, (I fully understand there is always a small chance for a brick but I mean is there a less chance)

**Comment by cheatfreak47** [comment]
Where on this github does this section say "Help and Support"?
Do not ask questions in the issues section, this is for reporting bugs and suggesting features.

To answer your question because I'm nice:
Luma3DS can run EmuNANDs running 11.0.0-33u and can also run 11.0.0-33u on SysNANDs via Arm9LoaderHax.

You can not hack 3DS consoles on stock SysNAND 11.0 without a hardmod beyond userland homebrew. 

Now close this issue, if you have further questions go to GBATemp or the 3DShacks Subreddit. 
This is NOT the place for it.

**Comment by JeanRiv** [comment]
Honestly, this stuff with people posting stuff like this on the Issues section is getting out of hand.

**Comment by TuxSH** [comment]
Indeed
