### ISSUE TITLE
blue light filter

### ISSUE THREAD

**Issue by T0biasCZe** [LumaTeam/Luma3DS#1384]
Hello, the bluelight reduce in screenfilters in rosalina menu (R+Ddown+select) work when started, but when the lid close and then open, the filter is off, and you need to turn it manualy again, which is annoying (mainly when you are playing in night and you close it and then open and the blue light shine at your eyes >_<)
steps to reproduce:
press R, down and select to open rosalina
Screen filters
select some level
close rosalina
close hinge
open hinge

**Comment by oreo639** [comment]
https://github.com/AuroraWright/Luma3DS/issues/1268

**Comment by suprstarrd** [comment]
This is intentional sadly, sleep mode bugs out from it

**Comment by T0biasCZe** [comment]
but in the #1268 issue, there is it mainly bugs on 2DS, which isnt closable. what about the new 3ds and new 2ds xl ?

**Comment by suprstarrd** [comment]
Can you read? The first two lines said it was done on New 3DS
New 2DS XL is probably the same

**Comment by vertexmachina** [comment]
If anyone is interested, I built a custom firmware with 7177799021109e9fb582c3a2832c390a679e66cc reverted and it works as expected on my New 2DS XL.

**Comment by vertexmachina** [comment]
@jbmagination 
@TuxSH 

For my own purposes, I modified the code to save the filter settings to a file and then read them from disk on boot.

It saves the color temperature (default: 6500) and whether the user wants to have the settings persist across sleeps (default: False).

Then, in Rosalina's main function, it loads the persistence setting from the file and, if it's true, creates the ShellOpen thread. If it's false then it does not create the thread. This way users can opt in to the feature if they want to see if it causes their console to hang on resume. If it does, no worries, reboot and disable persistence. If it doesn't, then they have the feature.

It also loads the saved color temperature from disk so that the setting persists across reboots, although you do have to put the unit to sleep and wake it back up again for it load them. I could not find a good place to automatically apply the saved temperature on boot without causing issues.

I also modified the color filter menu so that you can fine-tune the color temperature in increments/decrements of 500 rather than preset values like they currently are. I have a min of 2000 and a max of 6500 set, so you can do 2000, 2500, 3000, etc, up to 6500.

If this sounds like something you want added then let me know and I will submit a pull request.

**Comment by suprstarrd** [comment]
Do you mind adding that to my fork, [jbmagination/Luma3DS](https://github.com/jbmagination/Luma3DS)? I’d like to compile it with other stuff I have in my fork

**Comment by vertexmachina** [comment]
Sure! https://github.com/jbmagination/Luma3DS/pull/3

**Comment by TuxSH** [comment]
Intended, sleep mode wakeup detection caused issues
