### ISSUE TITLE
Add option to keep wifi enabled during GBA games and other virtual console games

### ISSUE THREAD

**Issue by electroniclogic** [LumaTeam/Luma3DS#1445]
I am trying to capture the screen while playing a gba game and the wifi shuts off, disabling the wireless capture. If you could somehow get this to keep wifi on it would be of great help.

**Comment by RocketRobz** [comment]
I believe it would also require Rosalina to keep running in the background, which afaik, isn't possible.
Same applies to DS(i) mode.

**Comment by Shadow322** [comment]
not gonna happen for GBA as when its running in GBA mode it is on bear hardware as GBA never had wifi

**Comment by profi200** [comment]
Not doable with official AGB_FIRM. Neither can Rosalina run under AGB_FIRM nor is WiFi fast enough to transfer RAW 240x160 frames. Not to mention there is barely enough memory available because FCRAM is disabled.

Capturing to the SD card is **maybe** possible but definitely not with official AGB_FIRM.

**Comment by TuxSH** [comment]
As profi said.

You're better off using something like mGBA on your PC for that use case instead.
