### ISSUE TITLE
Can't load homebrew like Decrypt9?

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#149]
Hello I'm trying to run Decrypt9 through hblauncher_loader but Decrypt9 just black screens. I've also tried loading the dat in ctrbootmanager but that froze also. Homebrew like FTPd works but nothing like EmuNAND9 or Decrypt9. I need a way to install a CIA manager to my EmuNAND and I was trying to do it with H&S inject. Is there a possibility it could be a patch in the CFW preventing it from loading and will there ever be a mode to load the CFW without any patches at all? The way I'm trying to load it through BrowserHax on 9.1JPN.

**Comment by ghost** [comment]
Oh also, what's weird is I used FBI through BrowserHax to install hblauncher_loader

**Comment by rsubtil** [comment]
Decrypt9 only works on 9.2 and below, I think. So, if you don't have A9LH to run it as a payload, I think you must downgrade, enev with CFW.

**Comment by ghost** [comment]
No the sysnand is on 9.1. And the sysnand is what the cfw is running.

**Comment by ghost** [comment]
You didn't read the OP did you?

**Comment by Hartie95** [comment]
You could try to use the latest version of decrypt9 WIP.

**Comment by SerLizar** [comment]
from Plailect's guide "Copy Decrypt9WIP.bin to the /luma/payloads/ folder on your SD card and rename Decrypt9WIP.bin to x_Decrypt9WIP.bin" then you can follow the instruccions on [part 4 section II of that guide](https://github.com/Plailect/Guide/wiki/Part-4-%282.1.0-Downgrade%29#section-ii---injecting-fbi) you just have to press x while booting your 3ds to boot directly into Decrypt9.

Edit: this happens because this homebrew requires arm9 access, which we don't have in firms past 9.2, but with a9lh we can still have access by running them before the firm finishes initializing, thus you need to run it as payload using Luma, another chainpayloader or replacing the arm9loaderhax.bin with the one of the homebrew you want to run.

**Comment by alvgalrus** [comment]
You'll need FW <9.2 AND signature patches enabled on your SysNAND for D9 to work. Your current CFW launches on SysNAND, but patches EmuNAND. You need a SysNAND CFW like MiniPasta to disable sigchecks on <9.2 SysNAND.

**Comment by ghost** [comment]
I seriously think none if you can read. I said I'm on 9.1. Since this will never be resolved due to a lack of brain cells I'll just close it.

**Comment by camatthew88** [comment]
Its okay

**Comment by spectron2077** [comment]
Try using slowhax or safehax

**Comment by Margen67** [comment]
*https://3ds.guide/

**Comment by spectron2077** [comment]
Bump

**Comment by ghost** [comment]
@camatthew88 I've already solved it, thanks though.

**Comment by urherenow** [comment]
Bump? Really? This isn't a forum. There's no such thing as a bump, and this issue was closed 7 months ago (ironic, since every reply afterwords suggests things that didn't even exist when this issue was closed)

SMH

**Comment by ghost** [comment]
xd
