### ISSUE TITLE
Manual of Out of Region Games does not work

### ISSUE THREAD

**Issue by ederenzi78** [LumaTeam/Luma3DS#150]
I have a EUR O3DS with A9LH and Luma 5.5 on SysNand. When I try to load the Manual of USA games, an error message pops up. Game has been downloaded using CIAangel and I created an entry in the locales directory to correctly handle the game. I tried for example "Sega 3D Classics collection" or "Kokuga".

**Comment by TuxSH** [comment]
Maybe it's just because the corresponding files from your region/language are missing?

**Comment by ederenzi78** [comment]
But I created a file in the locales directory to specify Region and Language for the title. In this case USA EN for a USA game. Luma 3ds correctly sees this file (infact, without it, Sega 3d classic does not save anything) but probably this is not seen for the manual .... I don't think CIAngel does not download the manual as it should download everything related to the title ...

**Comment by Hartie95** [comment]
From what I know the current region free menu patch is the problem, because it only patches the home menu to allow applications from other regions, but it is not skiping the check for manuals.
So to be able to use out of region manuals we would need a addition or new patch for the home menu.
This was also a problem when using it with the FreeMultiPatcher.

**Comment by TuxSH** [comment]
Are there really checks for manuals though? Or is it just the corresponding files for your language/region being missing from the manual files?

**Comment by piratesephiroth** [comment]
Manuals don't have icons therefore they're always region-free.

**Comment by Hartie95** [comment]
If its an out of region game, its possible to open manuals ingame, but the homemenu will give you an error. If you use NTR, is possible to open all manuals, without language emulation from what I know, so there needs to be a check somewhere.

**Comment by ederenzi78** [comment]
Can confirm that current region free menu patch is the problem, as with NTR manuals are correctly opened

**Comment by Margen67** [comment]
Why not just look through the source co- oh wait..

**Comment by d0k3** [comment]
Okay, my 5 cents. Manuals don't have a region that can be patched. The region is inside the icon (nowhere else) and CFAs like the manual have no icon. The manual also strangely works when there is a 'hard' regionfree patch inside the CXI icon (this means an edit of the actual CXI file, which is done by several CIA creator tools, f.e.). 

The issue is there for all out of region installs that don't have that regionfree patch, which includes, f.e. freeShop installs and CIAs created via several tools (like D9).

**Comment by sifiro** [comment]
But it's a little strange... (this is related with previous Issue) I Checked that my Cart (USA in EUR Console) can run manual out-of-region without any modification in cart. Musn't works the same patch for carts but for CIAs? if is a icon CXI Issue (and should have same or similar structure, It is not like this?).
Both have a CXI and CFA, (Difference between 3ds cart and installed title is cart have more partitions CFA)
https://www.3dbrew.org/wiki/NCSD
https://www.3dbrew.org/wiki/NCCH#Overview

**Comment by Hartie95** [comment]
Which games was it, maybe the game is regionfree(like the pokemon games).

**Comment by sifiro** [comment]
Senran Kagura 2: Deep Crimson (USA) and... I'm Pretty sure is Region Lock

EDIT: A moment, how a game can transform from Region Free (from Cart) to Region Lock (CIA). lol
My Issue is explained in https://github.com/d0k3/Decrypt9WIP/issues/116 (I thought was an Issue from D9 but is an Issue from Luma3ds appear)

**Comment by AuroraWright** [comment]
Should be fixed

**Comment by ghost** [comment]
To add onto what @AuroraWright said, manuals are now properly region patched as of commits 9f78d7f and b88dc9a.
