### ISSUE TITLE
Problem with Nintendo contract

### ISSUE THREAD

**Issue by Jose123456789007654** [LumaTeam/Luma3DS#1543]
I can´t accept Nintendo´s contract and I can´t play online or use spotpass or stretpass.

**Comment by Jack06WS** [comment]
Raising issues are like this are ridiculous. Nobody can help you if you spend 5 seconds on your issue request. Let us know lots of information such as your Luma3ds version, device model, firmware version. Provide images or videos.

Nobody will put effort in to help you if you can't put effort in for 5 minutes to type a helpful issue.

**Comment by ghost** [comment]
Check to see if this is a Luma3DS issue by doing the OFW safety test:

_SNIP unrelated/bad advice._
However, since you already posted it here, I will link you to this [EULA setter homebrew tool](https://github.com/noirscape/dses/releases/download/v1.1/DSES.cia)  (install it with FBI). If it doesn't work, then post the issue on [GBAtemp](https://gbatemp.net/forums/3ds-flashcards-custom-firmwares.201/create-thread).

**Comment by Jose123456789007654** [comment]
I did all of that, but when I get into the 3ds home page a few games that I had dowloaded dissapeard and when I updated my console it appeard it was updated. And I CANNOT enter to FBI. It´s like I eliminated all of the hack.

**Comment by ghost** [comment]
Strange. Did you try restarting your console?

**Comment by Jose123456789007654** [comment]
@dwain12435 If you mean by turning off and turning on the console, I did it and it didnt change anything.

**Comment by AuroraWright** [comment]
@dwain12435 what kind of advice is that? Please refrain from posting it. By following that procedure, if the update includes a NATIVE_FIRM update, you undo the b9s install (which is what happened to @Jose123456789007654 here probably). @Jose123456789007654 please install b9s again.

**Comment by AuroraWright** [comment]
About the issue at hand (which is completely unrelated to updating the console), that happens when the game is out of region. You need to use this homebrew app to set the EULA for all regions https://github.com/noirscape/dses/releases . No need to install the .cia by the way, the correct way to use homebrew these days is using the .3dsx with the HB menu if a 3dsx build is available. Closing here as it's not a support forum

**Comment by Jose123456789007654** [comment]
Hi @AuroraWright I might sound a little stupid but how do I install b9s?

**Comment by AuroraWright** [comment]
Follow the procedures to hack your 3ds again as if you'd never done it

**Comment by Shadow322** [comment]
> Hi @AuroraWright I might sound a little stupid but how do I install b9s?

https://3ds.hacks.guide/

**Comment by Jose123456789007654** [comment]
Thanks all!💞
