### ISSUE TITLE
All installed apps disappeared after system and Luma update

### ISSUE THREAD

**Issue by LabregoPT** [LumaTeam/Luma3DS#1568]
System model:
New 3DS XL

SysNAND version (+emu/redNAND version if applicable):

11.14.0-46U SysNAND

Entrypoint (How/what you're using to boot Luma3DS):

Boot9Strap

Luma3DS version:

v10.2.1

Luma3DS configuration/options:

Default EmuNAND: ( )

Screen brightness: 4(x)

Splash: Before(x)

Splash duration: 1(x)

PIN lock: Off(x)

New 3DS CPU: Off(x)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

Explanation of the issue:

I was running an old version of Luma, can't remember which one exactly, and decided to System Update. This version crashed Luma and had to update it as well. After update, the console booted to the main menu but all my homebrew and backups were not installed anymore. Checked the SD and it is completely fine, haven't tried formatting yet.
The Homebrew Launcher launches just fine, but trying to launch FBI.3dsx on it launches an Arm11 prefetch abort exception. Will provide the crash dump as soon as I'm able to.

Edit: While checking the SD, the files for both FBI.3dsx and ctr-no-timeoffset.3dsx were both of 0B. Corrupted files maybe? dunno.
Also tried to run GodMode9 by booting the console while holding start, but it simply won't boot. Gets stuck on a black screen and I have to turn off the console by holding the Off button

Steps to reproduce:

Dump file:
[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/5809655/crash_dump_00000000.zip)

**Comment by urherenow** [comment]
Checked your SD how? The usual culprits are corrupt sd card, corrupt tickets.db/titles.db (or simply "fixed" by sysnand since those things you installed aren't legit from Ninty), or outdated/incompatible software. First thing to try is a new card with the bare minimum on it to see if you can launch fbi. Make sure fbi is the latest also. In fact don't copy "the bare minimum" from your other card. Just your Nintendo folder, and download everything else from scratch. If you have problems there, try updating b9s or installing fastboot3ds.


GitHub is not a support forum. You'll get more, and perhaps faster answers on gbatemp.
