### ISSUE TITLE
Enable game update when 3ds is on 10.7-11.0 with non-official soft.

### ISSUE THREAD

**Issue by mariogamer2** [LumaTeam/Luma3DS#161]
Lot of user report (me too),that,when having non-copyrighted software on the 3ds (FBI,JKSM,SysUpdater),game update are somewhat "disabled".

Does it is possible to enable hem?

**Comment by Mrrraou** [comment]
non-copyrighted software != unofficial software
And what do you mean by that ? There are no software updates on the eShop for these.

**Comment by james-d-elliott** [comment]
You can game update via the eShop. The issue is that you cannot update USA titles on a EUR console because the DS downloads the EUR region update and the USA region game doesn't look for those files. When you launch it should ask you, if you have the EUR title and EUR console, you will update fine.

Edit: To clarify, each region should have it's own updates. I've never seen a case where it didn't work if you had the wrong region game. The only way to update these games is with CIA update packs.

**Comment by einstein95** [comment]
This is because afaik the game updates using the MINT module which has its own region-locking due to signing into Nintendo's services, basically acting as a mini eShop.
