### ISSUE TITLE
Cannot download game updates or Official themes, (ErrDisp)

### ISSUE THREAD

**Issue by MewtwoFanz** [LumaTeam/Luma3DS#1614]
I have been having this issue for awhile now, and I can't install updates nor official themes. This is what i get in my error:

An error occurred (ErrDisp)

Error type:    generic

Process ID:              19
Process name:         am
Process Title ID:       0x0004013000001502

Address:                  0x001093aa
Error Code:              0xd900182f

**Comment by urherenow** [comment]
Are you seriously trying to update online and even downloading official things from the eshop, while running CFW?


Try in OFW and see if you're banned.

Otherwise, there is a ton of info you're required to provide that you haven't. Like which firmware, system model, and Luma version you're currently running. And whether you're using b9s, fastboot3ds, a9lh, etc. Also what your Luma settings are. You know... like everything in the template you deleted instead of using...

**Comment by MewtwoFanz** [comment]
I meant game updates, not system updates. I should have clarified. My bad. I can still do system updates.

**Comment by MewtwoFanz** [comment]
I am running the latest firmware, 11.14, n3DS xl. I still need to look for the rest of the settings. I'll update this once I have them.

**Comment by Dimensional** [comment]
If your system is banned from online services, the only updates you can receive are system updates. Anything that requires downloading from the eShop, such as DLC, Game Updates, or Themes, will be blocked. I'm in the same boat with the same issues, and there is no way Luma can unban your system for these.

**Comment by MewtwoFanz** [comment]
I am not banned. These updates were working just fine before this problem occured.

**Comment by urherenow** [comment]
Can you open and browse the eshop?

**Comment by Dimensional** [comment]
> 
> 
> I am not banned. These updates were working just fine before this problem occured.

If you have "Use developer UNITINFO" enabled, disable it and try again. If you receive an error code with a message like "access to online services has been restricted by Nintendo", then your system has been banned. Don't just complain about it being the CFWs fault until everything else has been ruled out please, especially when there has been no information provided to rule it out. There is a very real chance that is the case.

Also to determine if it's a generic error, try disabling "ARM11 exception handlers", which is also found in the boot settings for Luma. This is only to get a better idea of what the problem is.

**Comment by MewtwoFanz** [comment]
I am able to enter the eshop, and my luma version is v10.2.1-4ae4d16d configuration. But it didnt matter what version I used, I still got the same error, even on the latest luma version.

**Comment by MewtwoFanz** [comment]
If this is important, I also have gm9, hourglass9, and decrypt9wip running

**Comment by MewtwoFanz** [comment]
I don't have disable Arm11 exception handlers enabled. It's always been disabled

**Comment by MewtwoFanz** [comment]
Set developer UNITINFO is also disabled

**Comment by MewtwoFanz** [comment]
I just tried it on luma v10.2.1-d0a44fd2-3gxldr configuration, still same error.

**Comment by MewtwoFanz** [comment]
The 3gx is the version i want to use

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
