### ISSUE TITLE
I have an issue with my new 2ds XL with luma and godmode9

### ISSUE THREAD

**Issue by gerkyo41** [LumaTeam/Luma3DS#1624]
I have my new 2ds xl with cfw magnethax using a R4. I on luma 9.1 and I can´t update it,I put the latest  version of luma 10
21 and replaced it with the old files,but when I turn on my 2ds holding select+power it shows me luma 9.1 and I don´t know why? I tried to access to godmode9 holding start+power buttons but nothing happens, it shows a black screen instead of godmode9 menu. I using the latest version of luma and godmode9, but doesn´t work for me.

Please I beg you somebody help me.

**Comment by urherenow** [comment]
The issues section of Github is for reporting bugs, not to be used as a help forum. 
If you're sure the files on your card are the latest, but it's loading 9.1, that would be because your system can't read your card, and you installed 9.1 to ctrnand in the past.

Turn it on without a card. Does it boot? Shows 9.1? This confirms the above.

Likely culprit: Corrupt card, incorrectly formatted card, or card reader damaged. There is a ton of info you haven't provided that's needed to aid in troubleshooting, but it's better for you to open a thread on gbatemp or ask in discord.
