### ISSUE TITLE
BootNTR CFW Selector stuck at Loading 3.6... after I select the version

### ISSUE THREAD

**Issue by upsideduck0** [LumaTeam/Luma3DS#1683]
Im using the latest version of Luma3DS and I installed custom firmware. My 3ds version is 11.15. I installed BootNTR Selector and it launches regularly. After selecting the 2nd option to the path configuration, I got to the version screen. Upon choosing either 3.6 or 3.3, my 3ds freezes at Loading 3.6/3.3 .... Does anyone know how to solve this? I'd appreciate alot.

**Comment by urherenow** [comment]
Github is not a support forum, and this isn't the bootNTR github page anyway.

**Comment by AlamosIT** [comment]
> Im using the latest version of Luma3DS and I installed custom firmware. My 3ds version is 11.15. I installed BootNTR Selector and it launches regularly. After selecting the 2nd option to the path configuration, I got to the version screen. Upon choosing either 3.6 or 3.3, my 3ds freezes at Loading 3.6/3.3 .... Does anyone know how to solve this? I'd appreciate alot.

Unfortunately the lastest official Luma build doesn't support NTR. If you want to use it you can use [this modified Luma build](https://github.com/Nanquitas/Luma3DS/releases), instead of the official one (AT YOUR OWN RISK), with the [latest version of BootNTR](https://github.com/Nanquitas/BootNTR/releases/latest).

I hope that in future official Luma will natively support video streaming, it is the only missing feature from NTR.
