### ISSUE TITLE
Autoboot crash when forcing shutdown

### ISSUE THREAD

**Issue by kynex7510** [LumaTeam/Luma3DS#1882]
When autoboot to 3DS is enabled, by forcing a shutdown (ie. holding the power button) NS will break on next boots. Booting with autoboot disabled solves the issue, but then debugging hostile homebrew that hang the system becomes really tedious.

**Comment by pdpapper** [comment]
Is there even any other way to shut the system down after you've autobooted a 3dsx? Short pressing the power button just freezes the system, so you have to force shutdown by holding the button...unless there's some other way I'm not familiar with?

This bug also affects autobooting into DSi/TWL mode. There's no error screen, but the system shuts down after a few seconds if you forced shutdown the previous time. The issue persists until you boot to the regular 3DS menu and shutdown properly.

**Comment by TuxSH** [comment]
This is a known issue I know happens when Home Menu fails to lauch when autobooted like that, but I'm not sure what's happening.

> Is there even any other way to shut the system down after you've autobooted a 3dsx?

Short press the POWER button and wait for a little bit for the Home Menu's shutdown screen to appear.

**Comment by pdpapper** [comment]
Short pressing the power button always locks the system for me if I autoboot a 3dsx. Is it really supposed to work? Autobot mem type is set to normal (0) in the ini. Trying other mem types, just results in an ARM11 exception (for 3dsx_app) at boot.

This is on a New 2ds LL, booted with fastboot3ds, and hbmenu 2.4.1 as boot.3dsx (as well as others).

I've also noticed that some 3dsx apps (DaedalusX64 especially) have graphical issues and are more pronr to crashing when I autoboot instead of going through the 3ds menu. I thought it was probably because some system services were unavailable, but maybe it's something else.

Rosalina is still available, though, I just hadn't noticed because it was still set to the default key shortcut. Shutting down through Rosalina does not interfere with the next boot.
