### ISSUE TITLE
.

### ISSUE THREAD

**Issue by kxws** [LumaTeam/Luma3DS#1891]

**Comment by skunkmommy** [comment]
1. please use the bug report template in future, errors can be caused by tons of stuff so bug reports should have as much information as possible. If you can't copy out the whole exception screen, take a **clear, legible, in focus** photo of your 3DS using something like a phone. **Do not touch the 3DS until you have taken the photo and confirmed that it is clearly readable.**
2. You need a fresh boot.firm. Redownload luma3ds and copy the `boot.firm` and `boot.3dsx` files to the root of your sd card. The root is the drive itself, not in any folders. When you double click a drive in file explorer, it brings you to the root of that drive.
