### ISSUE TITLE
hey guys i was wondering if you're going to add a patch that can bypass the latest 3ds update

### ISSUE THREAD

**Issue by tehyeetlord** [LumaTeam/Luma3DS#1893]
**System model:**

[New 2DS XL, New 3DS XL, New 3DS, Old 2DS, Old 3DS XL, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by Masamune3210** [comment]
There is no point. You already have a exploited console. Just update if you are bothered by the nagging.

**Comment by Shadow322** [comment]
> **System model:**
> 
> [New 2DS XL, New 3DS XL, New 3DS, Old 2DS, Old 3DS XL, Old 3DS]
> 
> **SysNAND version (+emu/redNAND version if applicable):**
> 
> [e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]
> 
> **Entrypoint (How/what you're using to boot Luma3DS):**
> 
> [e.g. Boot9Strap/Sighax, etc.]
> 
> **Luma3DS version:**
> 
> [e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]
> 
> **Luma3DS configuration/options:**
> 
> Default EmuNAND: ( )
> 
> Screen brightness: ( )
> 
> Splash: ( )
> 
> Splash duration: ( )
> 
> PIN lock: ( )
> 
> New 3DS CPU: ( )
> 
> --
> 
> Autoboot EmuNAND: ( )
> 
> Use EmuNAND FIRM if booting with R: ( )
> 
> Enable loading external FIRMs and modules: ( )
> 
> Enable game patching: ( )
> 
> Show NAND or user string in System Settings: ( )
> 
> Show GBA boot screen in patched AGB_FIRM: ( )
> 
> Set developer UNITINFO: ( )
> 
> Disable Arm11 exception handlers: ( )
> 
> Enable Rosalina on SAFE_FIRM: ( )
> 
> --
> 
> **Explanation of the issue:**
> 
> **Steps to reproduce:**
> 
> 
> **Dump file:**

The patch is to update and the nag will be bypassed

**Comment by ghost** [comment]
> There is no point. You already have a exploited console. Just update if you are bothered by the nagging.

It apparently does break exploits though.  While it would be incredibly hard to do, accidentally disabling or removing an exploit is not 100% outside of the realm of possibilities (especially systems allowed into the hands of children.)  The assumption seems to be that updating can't possibly cause any disadvantage, but it potentially can -- albeit in an extreme scenario.  This is putting aside paranoia some might have like if Nintendo is starting to slip in anything undesirable.  (I know it sounds unlikely, but come on, why are they even adding updates for the 3DS at this point when they officially have discontinued it?)  Conversely, there is absolutely nothing positive to be gained from doing the update at this point.  Absolutely no valid reason.  "Because it's inconvenient not to" isn't really a good reason to do anything.  Plus if they ever add yet another update it could eventually still potentially break Luma3DS (again with no actual valid reason to update by that point -- they're not going to add any value-adding functionality to discontinued hardware...  In fact, if anything, it's in their best interest to start removing functionality at this stage of things.)

In fact, I think that something to both the effect of the above and more might actually be a really good idea anyway.  Implementing disabling all phoning home features and disabling the phone home check when setting up a connection is actually a really good idea for the long term.  Currently things still mostly work, but with the 3DS officially discontinued eventually that will stop working.  As such, it will become seemingly impossible to even setup a new WiFi connection when their servers no longer work the same (which must surely happen some day even if possibly a very long time down the road.)  There's also no value or benefit to phoning home anymore either since stuff like online play and the eShop now no longer work directly.  Eventually those functions will stop working too and while it won't cause errors or crashes, it's still going to be trying to phone home at intervals whenever wifi is on.  It's wasting resources and ultimately some tiny bit of battery for functions that no longer have any actual value to the user.  I realize there's probably not much work being done on Luma3DS anymore and likely to be less and less going into the future, but that's all the more reason a more long term solution is probably a good idea implemented now rather than after it becomes a problem.

For now I'm using 90DNS because I don't want to do the update since, as I said, there are potential (even if unlikely) downsides and absolutely no upsides at all (plus I just don't want it phoning home anymore anyway.)  This does leave some concern of the possibility of MITM attacks unless I host my own server (which I currently can't do) but even putting aside the other concerns, it is tiresome having it download and attempt to install an update any time I enable the WiFi even just for a bit.

**Comment by Masamune3210** [comment]
Yeah...im not reading that brick wall of text lol
Does the update break exploits? Yes. 
Does that mean that a seemingly infinite list of others don't exist to use? No.
Can they do anything about Luma once its installed on a system? Not really, not in any real or permanent sense. This isn't the switch, the bootrom and early boot isn't just gonna change one day after an update.

There are only so many hours in the day and so many hands willing to whittle it away on this. Things might get fixed when and if they ever need to, but trying to push those hands to reach into the future isn't likely going to do much other than heat the air around you.

**Comment by ghost** [comment]
> Yeah...im not reading that brick wall of text lol

I don't see the humor in ignoring someone then responding to what you did (not) read into it.

What I'm saying is there are long term potential problems.  Putting aside that another update _could_ actually cause problems someday, there is the simple fact that things such as its phoning home at all could be a problem later on as servers eventually stop supporting the 3DS at all.  Some things -- such as the WiFi settings process -- even somewhat depend on that.  Rather than it keeping at such attempts, it's better if they are bypassed entirely.  Basically what Atmosphere does on the Switch.

**Comment by Masamune3210** [comment]
I don't see the point in typing a brick wall. I didn't read it, it's just really easy to guess what you said because it tends to be the same things that always get said. If you are truly worried about it, Luma is open-source, my point still stands. there are only so many people and so much time. If you are this adamant about it, feel free to work on implementing the changes

**Comment by TuxSH** [comment]
We expect people to run the latest firmware version, if anything
