### ISSUE TITLE
Luma v13.0 NDS(i) Mode broken

### ISSUE THREAD

**Issue by Devine3DS** [LumaTeam/Luma3DS#1919]
Hello,

Ive updated all my 6 3DS Consoles (NEW,OLD) to the latest Luma 3DS Version v13.0 and now on all the NDS Mode is broken.
Cartridges blackscreen after launching and TwilightMenu++ works until you load a game then the same happens.

All of the 3DSs have the Widescreen patches installed maybe thats the problem

It is the Widescreen patch it got moved from TwBg to the Luma Sysmodules and now its not working anymore.
If i delete the file from Sysmodules the Games work just fine but no Widescreen. I tried to move it back to TwBg it shows the Widescreen in TwilightMenu but then Blackscreens...

**Comment by Devine3DS** [comment]
Okay can be closed its fixed it was because i had a copy of TwBg laying in there

**Comment by JORGETECH** [comment]
This is caused by the latest Luma3DS version that added support for changing the scaling matrices in a similar way TWPatcher did (it also has the "unlocked DPad patch"), I guess the old method is incompatible and TWPatcher needs to be updated. The latest Luma3DS changelog explains the change and you can convert the old syntax to the new one with some Python code, sadly, there is no Widescreen patch and I don't know if RTCom patch has been implemented. If you want those features back I suggest downgrading to an old version of Luma3DS, the same thing I'll do since I also use those patches.
