### ISSUE TITLE
After activating the option Enable loading external FIRMs and modules on my 2ds, it is giving arm11 (core 1

### ISSUE THREAD

**Issue by Chuckiin** [LumaTeam/Luma3DS#2084]
Does anyone know if I should have any extra files? I've done everything, replaced the boot.firm manually and my Luma is version 13.1.2
![IMG_20240924_102345_005_LL](https://github.com/user-attachments/assets/52c4780f-9a35-460a-bc73-2b5bf84981af)

**Comment by TuxSH** [comment]
Hi, what is the content of `/luma/sysmodules` folder?

**Comment by EderParis** [comment]
I'm having the same problem, here's the crash dump.

[crash_dump_00000006.dmp](https://github.com/user-attachments/files/17180235/crash_dump_00000006.dmp)

**Comment by TuxSH** [comment]
Neither of you have answered the question. In the absence of details, and I think this is not caused by Luma3DS directly, I'll close the issue.

If I have to make a guess, this might be due to an old version of reHID and/or wuumibo that broke upon upgrading to Luma3DS v13.0. If you have these custom sysmodules, please update them to their latest release.

**Comment by EderParis** [comment]
Sorry I have no idea what I was doing, but I was in fact using and old version of reHID, I just update it and now everything is working fine.
Sorry for taking your time with some unrelated problem.
Thank you so much for helping me.

**Comment by TuxSH** [comment]
No problem :) In retrospect my message was rude, sorry.
