### ISSUE TITLE
Version string gets corrupted if customversion.txt is smaller than 19 bytes

### ISSUE THREAD

**Issue by Ennea** [LumaTeam/Luma3DS#221]
As the name states. If you don't use the maximum 19 bytes for customversion.txt, some (seemingly random) stuff gets appended to the version string.

**Comment by cheatfreak47** [comment]
pad it out with spaces

**Comment by Ennea** [comment]
Well, duh. Still a bug.

**Comment by Delphox** [comment]
Use an hex editor and add a "00" terminator.

**Comment by AuroraWright** [comment]
It's not a bug. You overwrite the "string" in the mset code (which is actually a sprintf argument) partially, and mset itself crashes. I allow partial overwriting of the string because one might want something like "A9LH" instead of "Ver." and the rest being the same. But you should be careful to overwrite it in a meaningful way.
You can do as Delphox said, or just pad it with spaces at the beginning if it's needed.
