### ISSUE TITLE
A way to raise maximum sound output (through headphones) 

### ISSUE THREAD

**Issue by Alicodemaker** [LumaTeam/Luma3DS#223]
Is there any way to put this in the settings?

**Comment by thejsa** [comment]
CTRAGING (Nintendo factory test app) can play sounds above [the normal] full volume, so I think this is likely to be possible one way or another.

**Comment by cheatfreak47** [comment]
This definitely should be possible within the limitations of the 3DS, knowing what CTR Aging is capable of.
Apparently AGING can set the volume level of the console, but won't save it because it won't pass the tests due to some unknown hardware related thing.

It's definitely something I'd love to see implemented, as long as it can be implemented in a relatively safe manner. (IE, not allowing it to be set so high, it blows out the 3DS speakers, for example)

**Comment by RinMaru** [comment]
@cheatfreak47 yea that was my concern. i have bluetooth headphones with a jack and it can boost the headphone volume instead of the systems

**Comment by fox8091** [comment]
For those of you REALLY interested, there was a hardware mod on GBATemp that upped the volume.

**Comment by Alicodemaker** [comment]
can you post the link or is it illegal?

**Comment by fox8091** [comment]
https://gbatemp.net/threads/hardware-mod-increase-the-earphone-output-volume-of-your-3ds-some-models-so-far.400221/

**Comment by piratesephiroth** [comment]
That hardware mod increases the earphone volume but not much. I think it gets like 20% louder at best.

**Comment by gudenau** [comment]
PLEASE DO NOT USE THAT MOD

Those resistors are there for a reason, they protect the 3DS!

**Comment by piratesephiroth** [comment]
protect from what

**Comment by gudenau** [comment]
ESD and shorts.

**Comment by Shadow322** [comment]
Resisters will explode

**Comment by gudenau** [comment]
Better than your 3DS, plus those are to encourage it to go somewhere else.

**Comment by Shadow322** [comment]
get one these
http://boostaroo.com/store/Boostaroo-Portable-Audio-Amplifier-and-Splitter-T613-BNC.html
