### ISSUE TITLE
Wiki: How to load GBA game

### ISSUE THREAD

**Issue by jvook** [LumaTeam/Luma3DS#244]
I can't figure it out from the wiki.   How do I load the GBA games?  Do I need to make a custom cia or not?

**Comment by Mrrraou** [comment]
yes or you use an emulator, that's not related to luma or its wiki

**Comment by jvook** [comment]
Ah so this part: 

> FIRM reboots replacement, which allows these to work:
> 3DS games which work in the larger RAM mode (Smash Bros, Monster Hunter 4... on Old 3DS)
> Custom GBA games
> Old DS flashcards

applies to VC injection as well as emulators?

**Comment by fox8091** [comment]
Only to VC emulation.

**Comment by fox8091** [comment]
s/VC emulation/VC injection

**Comment by jvook** [comment]
Right, so may that line would say "Custom GBA games with VC injection".  I'm not being pedantic, but took me about 30 minutes of googling and reading forum post to figure out how to load the GBA games with Luma3DS, but if it would say VC Injection I would know what to do.

**Comment by Mrrraou** [comment]
It means you can use custom GBA VC games... What is so hard to understand

**Comment by jvook** [comment]
It doesn't say VC at all on the wiki.  And, as you've said, there are at least two methods whereby GBA games can be played with Luma3DS.

**Comment by Mrrraou** [comment]
That's because the way Nintendo does their VC is without "emulators". And "Virtual Console" is a copyrighted product from Nintendo.

**Comment by cheatfreak47** [comment]
Heres a good tool for GBA VC injects
https://gbatemp.net/threads/release-ultimate-gba-vc-injector-for-3ds.438057/

A guide for making good use of the tool
https://gbatemp.net/threads/how-to-create-official-looking-virtual-console-injects.437592/

This can be closed now, as your issue really isn't an issue, have fun playing GBA games, mate. (:

**Comment by jvook** [comment]
Nah you guys are just attacking the user for inadequate documentation.  A google search brings all sorts of extraneous results.  A simple mention of VC cia injection on the wiki would be very helpful, as it's not clear exactly how luma3ds enables "custom GBA".  Indeed, a simple google search would suggest that the user install precisely the AGB_FIRM patches that the wiki warns against.  Furthermore, it would not be unreasonable to think that a raw GBA rom could be loaded and automatically injected by luma, which is not the case.  If you have the capability to close this issue, @cheatfreak47 , then it is your prerogative.  In the meantime, my wiki improvement suggestion stands.

To be precise, a search https://www.google.com/search?q=how+to+play+gba+on+luma3ds

The first result is a fairly useless thread full of confused users, though someone with your experiences may be able to deduce that CIA injection is needed.

The second result is a copy of the first

**The third result suggests patching AGB_Firm.**

etc.

On the other hand, a search for "how to do GBA CIA injection" would present the results that @cheatfreak47 has helpfully provided.  Therefore, it would be beneficial to mention VC injection on the wiki.

@Mrrraou Virtual Console is not copyrighted, it is trademarked. ("VC" is not, and cannot be trademarked).  In any case, "CIA injection" would suffice to return the correct search results.

**Comment by Mrrraou** [comment]
First, it's not "Custom GBA" but "Custom GBA games". Then, injecting those games has nothing to do with Luma. There is no reason for it to be on the wiki. The wiki isn't here because you can't do Google searches. The wiki only talks about the CFW itself. Luma says it supports custom GBA games and has no mention about the way they are loaded. It just supports booting those up, which is clear enough. 
Also, "Virtual Console" is a trademark, that's what I meant, yes. But Virtual Console games also contain copyrighted data.

In any case, this issue should be closed.

**Comment by Hartie95** [comment]
@Mrrraou you are right that the wiki is not there for people who can not do google searches, but I think it could be helpfull to clarify it a bit, because only gba Virtual console/gba injection will need the reboot patches at all, and thats the only reason for it to be in the wiki. For emulators the only helfull thing luma provides is svc backdoor access on newer firmwares, but thats something that is not worth to mention I think.

**Comment by TuxSH** [comment]
https://gbatemp.net/threads/release-ultimate-gba-vc-injector-for-3ds.438057/
