### ISSUE TITLE
SNES games won't load

### ISSUE THREAD

**Issue by SonicPrower** [LumaTeam/Luma3DS#260]
I have a n3ds with a9hl, my emunand and sysnand is both 9.2. Every time i boot Super Mario World, it gets stuck on the nintendo 3ds startup screen.

**Comment by ihaveamac** [comment]
update to the latest version.

**Comment by SonicPrower** [comment]
How do I do that?

**Comment by ihaveamac** [comment]
system settings?

**Comment by SonicPrower** [comment]
Do I update on emunand or sysnand? And if i update from emunand will it also update sysnand?

**Comment by ihaveamac** [comment]
whichever one has the game. no, they are separate (though there's no reason to keep them on 9.2)

**Comment by SonicPrower** [comment]
it worked. thank you so much, i was afraid to update emunand through system settings. i wanted to look it up before updating

**Comment by SonicPrower** [comment]
i tested the snes, game gear, gameboy, gameboy color and genesis emulator (3d sonic 2 app), they all worked except for gba and dsiware games. whenever i boot gba games it gives me an error and says press and hold the power button to turn the system off, whenever i boot dsiware games it gives me a black screen

**Comment by Margen67** [comment]
Why are you using emunand?

**Comment by Shadow322** [comment]
Because he wants to it's his choice dumbass

**Comment by cheatfreak47** [comment]
The reason you had a problem with SNES games is because they use 9.6+ Crypto, and the titles you installed were not crypto fixed for older firmware.

The reason you are currently having problems with GBA and DSiware games is because these cannot be played from EmuNAND without also needing to be installed on SysNAND.

EmuNAND/RedNAND is a deprecated feature due to its several shortcomings, one of which is that GBA and DSiware cannot be ran from it. 

While you are free to do whatever you want, it is recommended you migrate your EmuNAND into your SysNAND, [which is covered by Plailect's Guide.](https://plailect.github.io/Guide/move-emunand)

---

Please refrain from asking for support on  **github issue trackers.** 
This section is for reporting **actual problems with the software**, not asking for help when you don't understand something.

There are a number of proper places you can get answers to questions. Here are a few.
- GBATemp's 3DS Hacking Section
- the 3DShacks Subreddit Q&A Thread
- the 3DShacks IRC Channel
- the 3DS Hacking Discord in #help-and-questions

**Comment by AuroraWright** [comment]
What @cheatfreak47 said, although I wouldn't say EmuNAND is deprecated (it can be useful if you want different region NANDs or to go over the 200 titles limit, and it's the only choice if not using A9LH), it makes more sense for you to use SysNAND on A9LH in every other case though.
