### ISSUE TITLE
Add support for Wpa2-Enterprise

### ISSUE THREAD

**Issue by the4anoni** [LumaTeam/Luma3DS#261]
Please ,i have it in home and i host internet from phone to play online....................

**Comment by AuroraWright** [comment]
"Custom firmwares" aren't replacement operating systems despite their name, they're merely patchers for the Nintendo one.

**Comment by the4anoni** [comment]
So why not make a patch for wpa2 enterprise ?

**Comment by the4anoni** [comment]
But thanks for reply....

**Comment by cheatfreak47** [comment]
I'm pretty sure because of how the WPA2-Enterprise spec works, It's not something that you can just "patch in" unless you are Nintendo and you have a source code.

Why not just change the settings on your phone so the Wi-Fi isn't running in Enterprise? What kind of phone uses WPA2 Enterprise anyway? I have _never_ heard of that before.

**Comment by the4anoni** [comment]
No i said that my router broadcast wpa2 enterprice ,and i share wpa2 psk from my phone to use with 3ds.
Ok got it......

**Comment by cheatfreak47** [comment]
@the4anoni Ya know mate, you could probably just edit your router settings to use a different security type. Why the heck would you use Enterprise? Do you live in a cubicle?

**Comment by DaVinciLord** [comment]
@the4anoni you also can use a software to redistribute your internet through the wifi card of your computer if you have one (even if you access the web with said wifi card)
