### ISSUE TITLE
Multi Emunand

### ISSUE THREAD

**Issue by Aletron9000** [LumaTeam/Luma3DS#263]
I am having issues with emunand on a9lh (yes I know, it is useless, I just want it.)

when I change default emunand to emunand 3, it loads emunand 4
when I change default emunand to emunand 1 it loads emunand 2

I can tell because when I relaunch luma3ds settings, it says default emunand is either 2 or 4.

**Comment by Margen67** [comment]
> yes I know, it is useless

Just switch to Updated SysNAND, then.
If you're using A9LH then EmuNAND will provide you no more security than Updated SysNAND.
It's just a waste of SD card space.

**Comment by Aletron9000** [comment]
I have an updated sysnand. I use emunand for other regions. (Japan emunand, Europe emunand, etc). I use them quite often.

**Comment by fox8091** [comment]
Margen, how about instead of trying to convert people, you actually help with the issue. That would be nice. :) Anyways, I'll see if I can reproduce the issue.

**Comment by sora10pls** [comment]
He is helping by having them convert though :^)

**Comment by Shadow322** [comment]
No he fucking isn't just being a fucking ass

**Comment by cheatfreak47** [comment]
@Margen67 Hate to play devil's advocate here, but...

EmuNAND does have it's uses, particularly, it's good for bypassing that nasty 300 title limit,, it's kind of useful for testing something on a specific firmware version, and it's also useful for preventing degradation to the NAND chip.

For example, say you need to test home menu mods or something, an EmuNAND is a great benefit there, and multiple may even be considered beneficial if you were doing say, a custom home menu translation or something, or testing CIAs built for being installed to the NAND instead of the SD card.

I personally don't usually recommend it for typical users, but for those that are lazy and don't want to bother with the process for migrating nands, it's definitely not a feature that hurts anything by existing, I'd say.

**Comment by Margen67** [comment]
@Shadow322 Salty menuhax/emuNAND peasant detected.
Stop stalking me :^)

**Comment by AuroraWright** [comment]
Solved in nightlies
