### ISSUE TITLE
Custom hosts file to override dns

### ISSUE THREAD

**Issue by henke37** [LumaTeam/Luma3DS#271]
Hook the dns resolver to look in a hosts file before consulting the dns server.

**Comment by ioncorimenia** [comment]
Umm, [ctr-httpwn](/yellows8/ctr-httpwn/releases)?

**Comment by henke37** [comment]
That is only a partial solution. It does not address any protocols besides http. Especially not any custom protocols that may be game specific.

**Comment by henke37** [comment]
Why was this rejected?

**Comment by james-d-elliott** [comment]
1. You can set static DNS on most modern modem/router hardware.
2. You can setup a DNS server which does exactly what you want, look at BIND9.

Option 2 is better since you can manually set your DNS settings for the 3DS only. Additionally if you wish to do HTTPS you'll need this https://github.com/SciresM/3DS-SSL-Patch
