### ISSUE TITLE
Problem Loading

### ISSUE THREAD

**Issue by Slashin-it-up** [LumaTeam/Luma3DS#278]
I am having a hard time loading. On Ninjhax, it does all the colors and the gets stuck on black screens on top and bottom

**Comment by cheatfreak47** [comment]
In what world do you try to load Luma3DS with Ninjhax?

**Comment by Shadow322** [comment]
@HugaShine Just keep trying eventualy it will boot

**Comment by Slashin-it-up** [comment]
@cheatfreak47 this world

**Comment by Slashin-it-up** [comment]
@Shadow322 ok thanks

**Comment by Margen67** [comment]
Why would you use Ninjhax?

**Comment by cheatfreak47** [comment]
@HugaShire That ^
Sorry if I came of as an ass before, but what you're doing, booting luma with ninjhax is rather questionable.
There's almost no circumstance I can think of where booting Luma with Ninjhax is the appropriate course of action.

Like, you're not trying to load Luma3DS on a non-exploitable firmware are you?
Homebrew Launcher can only boot Luma3DS if the console is on 9.0 to 9.2, because it needs to use a kernel exploit that was patched on future firmwares.

You didn't really give a lot of info. You just dropped in saying "it doesn't work".
