### ISSUE TITLE
Out-of-region Nintendogs (Cia) will crash Luma3DS and the System (2DS 11.2.0-35U)

### ISSUE THREAD

**Issue by Slashin-it-up** [LumaTeam/Luma3DS#342]
My 2DS will crash when playing out of region (EUR Nintendogs + Cats Golden Retriever & New friends) and will give me this: 
[crash_dump_00000008.zip](https://github.com/AuroraWright/Luma3DS/files/720649/crash_dump_00000008.zip)

**Comment by Margen67** [comment]
Are you using A9LH?

**Comment by Slashin-it-up** [comment]
Yes.

**Comment by MelonGx** [comment]
Nintendogs is a special game which ALWAYS requires region presetting.
So you SHOULD always build a TXT file on /luma/locales/ for Nintendogs and enable "Enable region/language emu. and ext code" on Luma settings.

You should report an issue AFTER being done of this.
If you don't, then it's caused by your incomplete preparation of running this game, but not Luma's issue.

**Comment by Slashin-it-up** [comment]
ok
