### ISSUE TITLE
Gba virtual consoles screen issues

### ISSUE THREAD

**Issue by jcmejia** [LumaTeam/Luma3DS#355]
Gba virtual consoles have screen issues on luma3ds 6.6 firmware 11.3.0-36u

**Comment by Margen67** [comment]
What is the allocation unit size of the SD card?

**Comment by jcmejia** [comment]
128gb

**Comment by jcmejia** [comment]
On new 3ds

**Comment by jcmejia** [comment]
It was working fine on 11.2 on luma3ds

**Comment by piratesephiroth** [comment]
what's even a screen issue?

**Comment by jcmejia** [comment]
After I updated Luma to 11.3 it started having issues

**Comment by jcmejia** [comment]
Try a gba virtual consoles on Luma3ds on firmware 11.3

**Comment by jcmejia** [comment]
The resolution is messed up I'd post a pic of it but I don't know if I could

**Comment by cheatfreak47** [comment]
@jcmejia

>128GB 

Bingo, I've found the issue.

Basically, GBA games sometimes have an issue where the screen is mapped improperly when using a card that is too slow. **This is not a Luma issue, this happens even on stock systems.** 128GB cards tend to not be as fast as smaller size cards, which may be the cause here.

As @Margen67 was asking, the allocation unit size (sometimes called cluster size) can also have an impact on this, so your only hope of fixing this issue is to change it.

The best course of action is to backup your entire SD card to your computer and format the SD card using this [tool](https://cdn.discordapp.com/attachments/265713680560160768/278579320287395840/guiformat.zip).

When formatting set the Allocation Unit Size to "32768", and make sure you pick your SD card and not some other important drive, and from there, if you are lucky, the GBA issue will disappear, otherwise tough luck, it's nothing we can just fix.

Then restore the backup of the SD you made before formatting.

In the meantime, this is not only a non-luma issue, but also a duplicate of an issue that was already closed, and thus this should also be closed.

**Comment by shinji257** [comment]
Duplicate: https://github.com/AuroraWright/Luma3DS/issues/142

**Comment by jcmejia** [comment]
The cluster size I don't know but I will check it later but I think it's a
32kb cluster

**Comment by jcmejia** [comment]
Besides that it was working fine until I updated Luma to
11.3

**Comment by cheatfreak47** [comment]
Look, I know exactly what your issue is and I've done research into it personally, and I'm telling you the issue is definitely related to SD card speed **and has nothing to do with the update, nothing to do with Luma, and nothing to do with hacking either.**

Nintendo hasn't touched AGB_FIRM since ~they added it with the ambassador
 program back when it was introduced~ firmware update 6.0, which was well over 2 years ago.

You probably just never encountered the issue before, because it's not entirely consistent.
It happens seemingly randomly with different SD card sizes and cluster sizes.

**Comment by jcmejia** [comment]
So what do you recommend

**Comment by cheatfreak47** [comment]
What I said above, reformatting the card as FAT32 with 32,768 bytes per allocation unit (cluster size) and hoping the issue goes away.

If it doesn't either deal with it or get a 64GB SD card instead and deal with the spacial limitations that comes with.

Those are the only options for fixing it, unfortunately.

**Comment by Margen67** [comment]
Or you could use a GBA emulator

**Comment by Rust-and-Sunset** [comment]
Obviously, this isn't a Luma issue- but I have noticed that this issue only crops up in certain titles.

Kurukuru Kururin, for example, exhibits the issue- whereas, say, FF Tactics Advance doesn't. Might explain why @jcmejia didn't notice the issue previously - if they're trying a VC inject they hadn't used prior to upgrading Luma version, and it happens to be one of the unlucky ones, they wouldn't have any idea what prompted the change. 

If you'd like some confirmation, try some other games.

**Comment by jcmejia** [comment]
Actually it was happening with sonic advance 2 and 3 on emunand but not on
system nand

**Comment by jcmejia** [comment]
But I did notice a slight fix by pressing the home button a couple of times

**Comment by Rust-and-Sunset** [comment]
> But I did notice a slight fix by pressing the home button a couple of times

...Strange. This does actually have an effect- rapidly tapping the Home button shifts the output up by a certain interval on each press. Seems to take place during the transition time between the back-to-Home-Menu dialog being called and its pop-in animation completing. 

This is the result:

![vcinterval](https://cloud.githubusercontent.com/assets/13955128/22764253/6ba6a592-ee61-11e6-83e2-818d16ce16e2.jpg)

By repeatedly doing that, it's possible to make the output loop all the way around, making it output correctly. Takes about a minute or so of tapping, tops.

Peculiar bug.

(It also doesn't seem to trigger if you force pixel-perfect output by holding Start as you boot the title- definitely an option worth considering, if you don't want to bother with the above solution.)

**Comment by jcmejia** [comment]
Yes that's exactly what I did but for me it was less than a minute

**Comment by Margen67** [comment]
This is why you shouldn't use emuNAND.

**Comment by Rust-and-Sunset** [comment]
It's not just an EmuNAND issue, @Margen67 - I can reproduce it from SysNAND.

Not really a big deal, I suppose. Would be nice to have some kind of way of preventing it happening, but that moves well out of bug report territory into feature requests.

**Comment by jcmejia** [comment]
So should I use system nand

**Comment by Rust-and-Sunset** [comment]
@jcmejia This isn't really the correct place to ask for general tech support. I recommend asking in [/r/3dshacks'](http://reddit.com/r/3dshacks/) Q&A thread. 

(But, yes- you should transfer your EmuNAND setup to SysNAND. Ask in the Q&A thread if you're not sure how that's done.)

**Comment by urherenow** [comment]
So... yes, the screen scrolling with the home button IS a bug. 

But for future reference, VC titles from emunand pose a problem on a variety of setups (hacky reboot patches required to work AT ALL in the case of GBA stuff) so it is best practice to use sysnand for VC. The latest guides for a9lh don't even bother telling you to make an emunand anymore.

**Comment by Margen67** [comment]
>it is best practice to use sysnand for VC.

It's best practice to use sysNAND for everything not just VC unless you're a developer, want to bypass the 300 title limit, or region change. Otherwise it's just a waste of SD card space.

**Comment by jcmejia** [comment]
I will probably stick with emunand cause I haven't installed a9lh before I
heard it's very risky due to random bricks I'm actually more skilled with
wii/wii u modding I'm actually still learning on 3ds modding I'm actually a
fast learner when it comes to modding besides that thanks for letting me
know about a9lh I might install it sometime in the near future.

**Comment by Margen67** [comment]
@jcmejia All bricks are due to user error.
As long as you follow the guide you won't brick. https://3ds.guide/
