### ISSUE TITLE
Black screen latest nightly 11.4 firmware

### ISSUE THREAD

**Issue by teuf504** [LumaTeam/Luma3DS#401]
Hello

I updated Luma to the latest nightly in order to update my firmware to 11.4.

I get the purple menu from Luma whenever I boot my o3DS (as usual) but when I launch boot.3dsx I get stuck in a non-ending black screen.

Anyone might know how I can get me un-stuck?

**Comment by Margen67** [comment]
What entrypoint are you using?

**Comment by teuf504** [comment]
OoTHax to install menuhax since my o3DS was unwilling to use menuhax from the get go a year or two ago.

I don't use soundhax nor safehax so it shouldn't be a problem with the new firmware based on what I read

**Comment by guiscaranse** [comment]
There is no *hax support for 11.4 yet

**Comment by Margen67** [comment]
@teuf504 https://3ds.guide/

**Comment by teuf504** [comment]
@guiscaranse Then Luma isn't too, to the contrary of what's written in many places, since a9lh is also a *hax

@Margen67 A9LH is installed on my o3DS since I updated to Luma though. The last part of the guide is completed. The only difference is that I still use an emuNAND rather than the sysNAND because I prefer to do so

The only thing I don't have is GodMode

**Comment by Margen67** [comment]
If you have A9LH why did you say

>OoTHax to install menuhax since my o3DS was unwilling to use menuhax from the get go a year or two ago.

>I get the purple menu from Luma whenever I boot my o3DS (as usual) but when I launch boot.3dsx I get stuck in a non-ending black screen.

If you have A9LH you should just use the HBL CIA.

>Then Luma isn't too, to the contrary of what's written in many places, since a9lh is also a *hax

what

**Comment by teuf504** [comment]
> If you have A9LH why did you say

Because I use the boot.3dsx meant for menuhax that's in the Luma3DS archive. Hence the fact I say I'm using menuhax as an entry point

> If you have A9LH you should just use the HBL CIA.

I can't

> what

It's called arm9loaderhax so it's a *hax. If no *hax is supported on 11.4, then Luma shouldn't work at all, which isn't the case unless I'm mistaken

**Comment by cheatfreak47** [comment]
@teuf504 
First of all Arm9LoaderHax is not a *hax. It's a special entrypoint for running Arm9 code at boot, not running userland Arm11 homebrew. (Which is what we call *hax in this scene)

Because you're over here spouting off only random bits of information about your 3DS, we're unable to understand what exactly your 3DS's setup is like and can't help.

You shouldn't be using MenuHax, nor should you be getting any kind of "Purple Menu" unless you are running with an extremely outdated setup- meaning you **don't** have arm9loaderhax installed.

If you have Arm9LoaderHax, you should be running Luma 3DS with a CFW SysNAND, which should be updated to at least 11.3 by this point. If you need to launch .3dsx homebrew or run the Homebrew Launcher, you would be doing that by running Yellows8's Homebrew Launcher Loader (which is installed as part of 3ds.guide)

3ds.guide sets you up with Luma 3DS booting as a Arm9LoaderHax Payload- and if you have Arm9LoaderHax, all you do to update Luma yourself is replace the old "arm9loaderhax.bin" on the SD card root with the newest one. Hamcha's Luma 3DS Updater does this on-console without the need for a computer or anything.

Lastly, from the sound of things, this is a USER issue, not a problem with the Luma3DS software.
Meaning, you shouldn't be seeking help _here._

Go to one of these places instead.
/r/3dshacks: http://reddit.com/r/3dshacks/
Nintendo Hacking: https://discordapp.com/invite/C29hYvh
IRC: #3dshacks@rizon

**Comment by gnmmarechal** [comment]
They probably think they have A9LH because the payload is named arm9loaderhax.bin . Oh well.

**Comment by MelonGx** [comment]
All entrypoints use arm9loaderhax.bin since 6.3:
- MSET -> Luma3DS.dat (6.3.1) -(redirect)-> arm9loaderhax.bin
- Spider -> Luma3DS.dat (6.3.1) -(redirect)-> arm9loaderhax.bin
- *hax -> Boot Manager for *hax -> Luma3DS.dat (6.3.1) -(redirect)-> arm9loaderhax.bin
- *hax -> boot.3dsx (Luma) -> arm9loaderhax.bin
- *hax -> Boot Manager for *hax -> boot.3dsx (Luma) -> arm9loaderhax.bin
- A9LH -> arm9loaderhax.bin
- A9LH -> Boot Manager for A9LH -> arm9loaderhax.bin

So it's stupid to say using arm9loaderhax.bin == 100% a9lh.

**Comment by gnmmarechal** [comment]
Yep, but this misconception is fairly common.

**Comment by AuroraWright** [comment]
Fixed
