### ISSUE TITLE
[Feature Request/Issue] fix *hax payloads/*hax payloads crash

### ISSUE THREAD

**Issue by qimiko** [LumaTeam/Luma3DS#495]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.3.0-36U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v8.0

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (1)

Splash: (Before)

PIN lock: (Off)

--

Autoboot EmuNAND: (Off)

Use EmuNAND FIRM if booting with R: (Off)

Enable loading external FIRMs and modules: (Off)

Enable game patching: (Off)

Show NAND or user string in System Settings: (On)

Show GBA boot screen in patched AGB_FIRM: (On)

Patch ARM9 access: (Off)

Set developer UNITINFO: (Off)

--

**Explanation of the issue:**

With the new homebrew launcher, you can't run anything that requires a target title (like JK's Save Manager or HANS)

However, trying to load the old homebrew launcher results in a crash, and if you use the homebrew launcher loader, then homebrew crashes on load.

Also, DSP Dump requires a hax 2.x payload, which doesn't work on Rosalina (it's completely possible that DSP Dump just needs to be updated)

**Steps to reproduce:**

1. Load the old homebrew launcher using homebrew_launcher loader

2. Load a title

3. CRASH

**OR**

1. Load the homebrew launcher using a payload like soundhax

2. CRASH

I've uploaded 4 dump files in arm11.zip

[arm11.zip](https://github.com/AuroraWright/Luma3DS/files/1051076/arm11.zip)

**Comment by blackwing182** [comment]
All hax payloads are obsolete for now on.

**Comment by qimiko** [comment]
I know that, but some homebrew rely on the hax payloads, and probably won't be updated for the Rosalina entrypoint. (And I don't know how to update homebrew to use the Rosalina entrypoint)

Maybe a setting, if the hax payloads were disabled by choice, instead of Rosalina not being able to run with other entrypoints.

**Comment by fincs** [comment]
hax payloads by design cannot work under Rosalina because the memory map is shuffled around to make space for the Rosalina system module to load (and this breaks the hax payloads because they expect certain things to be at fixed locations in memory).

It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

There should be a replacement for DSP Dump soon.

**Comment by BigBrainAFK** [comment]
Use CIA versions of anything you can as they most often work way better (at least when +hax was a thing)

**Comment by fincs** [comment]
With Rosalina 3dsx no longer has ARM11 FS/svc permission or code size limits (and the default service access list is pretty complete), so 3dsx running on Rosalina should be as good as installed applications.
