### ISSUE TITLE
Black screen when trying to boot Rosalina

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#517]
When I try to open Rosalina the screen keeps black and I need to shotdown. I have Luma 8.0 and boots9trap 1.2, on a old 3ds 11.4

**Comment by Nyquis** [comment]
It is due to the way _while_ can be interpreted.

I urge devs to find a better way to formulate in the release notes and on the guide.

What they mean is once the 3ds is fully booted you can press the key-combe to open Rosalina menu. Do not press it during the booting process because you will get stuck.

**Comment by ghost** [comment]
Ok, thanks
