### ISSUE TITLE
Rosalina/3DSX: HANS-derived homebrew no longer works

### ISSUE THREAD

**Issue by Wack0** [LumaTeam/Luma3DS#547]
**System model:**

Old3DS

**SysNAND version (+emu/redNAND version if applicable):**

10.3.0-28E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

HANS and HANS-derived homebrew no longer works, upon starting the game a data abort exception occurs.
(I know that with Luma and Rosalina you can just patch games directly. HANS-derived homebrew not working, however, breaks backwards compatibility.)

Not only this, the crash dump created is partially broken.

**Steps to reproduce:**

1. Set up the homebrew app for a game, run HANS, start the game

2. Data abort exception, creates a partially broken dump

**Dump file:**

[crash_dump_00000141.zip](https://github.com/AuroraWright/Luma3DS/files/1054840/crash_dump_00000141.zip)

**Comment by fincs** [comment]
This is intentional. It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

Also, HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature.
