### ISSUE TITLE
[Rosalina] Add support for launching applications under target titles

### ISSUE THREAD

**Issue by Link2738** [LumaTeam/Luma3DS#555]
Can this be a feature or will we have to use a different exploit?

**Comment by fincs** [comment]
Duplicate of #547 and fincs/new-hbmenu#4

This is intentional. It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

Also, HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature.

**Comment by Link2738** [comment]
I wasn't asking about save files I was asking about apps like braindump to dump game assets

**Comment by TuxSH** [comment]
Same thing.

Use GodMode9 for the latter.

**Comment by Link2738** [comment]
Like models,textures,ect. I know there are savemanagers galore on gbatemp
EDIT: (I'll get an old 3ds and dump them on that) Still good work on 8.0

**Comment by Znethix** [comment]
just delete the .xml file.

I ran braindump and it worked but it doesnt let me choose the program.  Help

and what do i have to do?

**Comment by fincs** [comment]
Use GodMode9 instead of braindump for dumping game assets.
