### ISSUE TITLE
[Suggestion] Add screen brightness adjustment option into Rosalina Menu

### ISSUE THREAD

**Issue by ZenithRogue** [LumaTeam/Luma3DS#571]

**Comment by ahoischen** [comment]
First of all, this seems to be a duplicate of #59 which is now over one year old. The maintainers should decide on how this is handled. I also request the issue description to be trimmed since it doesn't include any content. 

The suggestion seems to be to add a backlight adjustment to the Rosalina menu. It is most likely derived from NTR's backlight control and seems useful for those times when the home menu isn't accessible. While fine-grained control is nice, I don't see it as necessary since the home menu is now available at any time that Rosalina is.

**Comment by TuxSH** [comment]
Will be added.

**Comment by ghost** [comment]
See the reference. Closing this now. Thank you.

**Comment by CookieXD** [comment]
How long will it take to add it? Can't wait anymore... (I am very impatient)

**Comment by ghost** [comment]
Entitlement won't get you anywhere.

**Comment by CookieXD** [comment]
I just was curious how long it might take... Guess I just have to wait.

**Comment by Shadow322** [comment]
2-4 years

**Comment by CookieXD** [comment]
`2-4 years` seems obvious to me.

**Comment by Shadow322** [comment]
And might even take as long as 5 1/2-6 years
