### ISSUE TITLE
Clock+L2 defaults to On in Rosalina, even when turned off in Luma config

### ISSUE THREAD

**Issue by snk3dive** [LumaTeam/Luma3DS#593]
Every time I boot, I have to turn off Clock+L2 manually, because Rosalina seems to ignore the Luma config option.

**Comment by Clement95** [comment]
If you want to turn off cpu clock, turn off it in the Luma config

2017-06-11 20:16 GMT+02:00 Garrett Monteiro <notifications@github.com>:

**Comment by bakugo** [comment]
The N3DS menu in rosalina doesn't update when the clock changes (when you have Clock+L2 disabled, the clock changes to O3DS values when you start a game that doesn't use N3DS values) but don't worry, it's still disabled.

That said, it really should be changed to update every time the menu is accessed.

**Comment by ghost** [comment]
The Rosalina menu currently doesn't update to reflect changes in clock rate/L2 cache; they display as on because the Home Menu runs in Clock+L2 mode stock/by default on N3DS. Despite this, the values are actually being changed normally when opening an non-N3DS enhanced title, provided you haven't forced them with the config menu option.

**Comment by ghost** [comment]
This has been fixed in the latest commit. Thanks for the report.
