### ISSUE TITLE
Luma 8.0 Homebrew launcher 2.0 Some Apps not working

### ISSUE THREAD

**Issue by yukos10** [LumaTeam/Luma3DS#638]
New 3DS

11.4.0-37e

Boot9Strap

Luma 8.0

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( x)

Show NAND or user string in System Settings: ( x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

After the update luma 8.0 and homebrew launcher some apps not working anymore(phbank, save_manager ). laucher said: This homebrew exploit does not have support for launching applications under target titles please use a different exploits.

**Comment by fincs** [comment]
This is intentional. It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

Also, HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature. You can also use GodMode9 instead of braindump for dumping game assets.
