### ISSUE TITLE
Luma v8 wont let me use Braindump in homebrew because it doesnt support target titles

### ISSUE THREAD

**Issue by TKSTScopinator** [LumaTeam/Luma3DS#649]
sighax 1.2 obviously and im using hblauncher_loader cia maybe if i use a different exploit it might work but idk how to get another

**Comment by TKSTScopinator** [comment]
sighax 1.2 obviously and im using hblauncher_loader cia

**Comment by fincs** [comment]
This is intentional. It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

Also, HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature. You can also use GodMode9 instead of braindump for dumping game assets.
