### ISSUE TITLE
Battery charge issue

### ISSUE THREAD

**Issue by RS55** [LumaTeam/Luma3DS#716]
Before installing any CFW to my 3DS (then RXtools), that is to say with OFW, buy a Nyko Power Pack for my O3DS and had an average of more than 8/10 hours per load as a minimum with everything off (wifi on, 3D, Lighting level 1, power saving on...), But I have noticed that from a time to here with the latest updates of Luma3DS (not to say exactly) and now with the rosalina menu I have confirmed that it no longer does the battery calculation as it originally did with OFW.

Last night I did the test waiting for it to reach the 01% and started to count the hours that lasted on, previously had played about 4 or 5 hours with everything to the maximum, then put super smash bros as it is more demanding for the system and leave fighting the CPU (vs 4 CPU), in total the console hard between 3 and 4 hours more in 01% with the LED flashing.

So, I thought my battery was being damaged but it seems the opposite, maybe this also affects other users even using the original battery because long ago I read users asking if Luma3DS with A9LH consumed more battery and then they think that they have a low load, but the battery actually has more

**Comment by clemperorpenguin** [comment]
I have the same extended battery. I can test this tonight probably.

On Jul 9, 2017 4:07 PM, "RS55" <notifications@github.com> wrote:

Before installing any CFW to my 3DS (then RXtools), that is to say with
OFW, buy a Nyko Power Pack for my O3DS and had an average of more than 8/10
hours per load as a minimum with everything off (wifi on, 3D, Lighting
level 1, power saving on...), But I have noticed that from a time to here
with the latest updates of Luma3DS (not to say exactly) and now with the
rosalina menu I have confirmed that it no longer does the battery
calculation as it originally did with OFW.

Last night I did the test waiting for it to reach the 01% and started to
count the hours that lasted on, previously had played about 4 or 5 hours
with everything to the maximum, then put super smash bros as it is more
demanding for the system and leave fighting the CPU, in total the console
hard between 3 and 4 hours more in 01% with the LED flashing.

So, I thought my battery was being damaged but it seems the opposite, maybe
this also affects other users even using the original battery because long
ago I read users asking if Luma3DS with A9LH consumed more battery.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AuroraWright/Luma3DS/issues/716>, or mute the thread

**Comment by ghost** [comment]
Duplicate of other reports. This is pretty much impossible; Luma will not cause any significant battery drain over stock. See [here](https://en.wikipedia.org/wiki/Lithium-ion_battery#Degradation) and [here](https://en.wikipedia.org/wiki/Nocebo). Additionally, having first experienced the issue with other, unrelated custom firmwares also points to this issue not being Luma's.

**Comment by RS55** [comment]
Well I doubt very much that it is degradation of my battery because it still works as the first day in terms of duration as I said before and believe me, I would not make a subject regarding this without knowing anything about how a Lithium-ion battery works, but good for me is no coincidence that the percentage is affected just when I pass to luma because otherwise the battery would NEVER last for almost 4 hours at 01% but well... I just say.

**Comment by ghost** [comment]
Looking at that device, it's actually an extended battery that replaces the original back plate; given this, incorrect reporting isn't surprising. Many devices assume a certain capacity when doing battery life calculations; this issue also occurs on PS4 controllers, for example.
