### ISSUE TITLE
Rosalina increased battery compustion

### ISSUE THREAD

**Issue by MissPotato** [LumaTeam/Luma3DS#764]
**System model:** Old 3DS

**SysNAND version (+emu/redNAND version if applicable):** Don't know, so assume N/A

**Entrypoint (How/what you're using to boot Luma3DS):** Soundhax/Boot9Strap

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:** 8.1.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (4)

Splash: (after)

PIN lock: (off)

New 3DS CPU: (n/a)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: (x)

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Noticeable decrease in battery life when leaving Roslilina open and closing the lid. The battery won't even make it a full night with Rosalina open while with it closed about a week of idle time is my average.

**Comment by clemperorpenguin** [comment]
Why leave Rosalina open overnight?

On Aug 7, 2017 8:13 PM, "MissPotato" <notifications@github.com> wrote:

*System model:* Old 3DS

*SysNAND version (+emu/redNAND version if applicable):* Don't know, so
assume N/A

*Entrypoint (How/what you're using to boot Luma3DS):* Soundhax/Boot9Strap

[e.g. Boot9Strap/Sighax, etc.]

*Luma3DS version:* 8.1.1 stable

*Luma3DS configuration/options:*

Default EmuNAND: (1 )

Screen brightness: (4)

Splash: (after)

PIN lock: (off)

New 3DS CPU: (n/a)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: (x)

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

*Explanation of the issue:*
Noticeable decrease in battery life when leaving Roslilina open and closing
the lid. The battery won't even make it a full night with Rosalina open
while with it closed about a week of idle time is my average.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AuroraWright/Luma3DS/issues/764>, or mute the thread

**Comment by ghost** [comment]
Sleep mode doesn't work when the Rosalina menu is open, known issue.

**Comment by MissPotato** [comment]
Oh, it didn't even link up in my head that sleep mode was what was saving battery. Sorry for the duplicate!
