### ISSUE TITLE
ARM11 Crash error (core1)

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#805]
Hi everyone, after release of RpwnG exploit i try it but when i select the file, i have in a seond the Homebrew pop up and after a crash error with ARM11 (core 1) with data abort in Menu there my .dmp file
[crash_dump_00000042.zip](https://github.com/AuroraWright/Luma3DS/files/1238714/crash_dump_00000042.zip)

**Comment by Committee** [comment]
No offense to RPwnG but why do you need it if you already have Luma running?

**Comment by ghost** [comment]
I want run Homebrew channel because with Rosalina some app can't be run

**Comment by fincs** [comment]
hax 2.x cannot run under Luma3DS due to differences in memory addresses required by it.

With regard to Rosalina not supporting some apps: this is intentional. It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

Also, HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature. You can also use GodMode9 instead of braindump for dumping game assets.
