### ISSUE TITLE
Add support for DLC patching

### ISSUE THREAD

**Issue by mariomadproductions** [LumaTeam/Luma3DS#829]
Suggestion: Add support for patching DLC titles. DLCs have multiple "app" files, which means multiple RomFSs. Luma3DS does not seem to have support for this from reading the wiki.

**Comment by ghost** [comment]
This is likely infeasible; the mounting locations are unknown and are probably game-specific. If not, this might be possible.

**Comment by mariomadproductions** [comment]
I don't really understand why this would be infeasible just because they are game specific. There could be a Title-MountingLocation list or instead couldn't they be autodetected by looking at the game's code/actions?

**Comment by jonirrings** [comment]
@mariomadproductions 
yes, it can't be autodetected by looking at the game's code.
cause every game has its own binary layout/mapping, and it own logic to decode the mapping.

that is the difficulty what the community translation groups had encountered.
every game requires manual reverse engineering, then replace the text and assets~~~

**Comment by mariomadproductions** [comment]
Could it be autodetected by looking at what locations the game tries to use while it is running?

**Comment by jonirrings** [comment]
logically possible, but that requires much much work.
a program can't distinguish whether the game is fetching a code or an asset, because it is game-specific, it will vary every time. the code in one game may look like an asset in another one. 
so for "auto-detect", you should specify rules for the program to judge, even for a HACKER, what she/he did is "guess and try", based on her/his experience.

as said above, every game has its own binary layout/mapping, without this, code looks the same as asset, and you can't tell the border of them. to get this, you have to analyse every game manually. that is why it is hard to make "auto-detect".

**Comment by mariomadproductions** [comment]
I'm not really following. The code is in a separate file to the assets: ``.code`` in the ExeFS. Also, won't the code use some kind of service to get the DLC data? And doesn't DLC always have some kind of ``SOMETHING://``string in the code like ``BIGRED://`` in New Super Mario Bros. 2?

**Comment by TuxSH** [comment]
Closing, tracker cleanup
