### ISSUE TITLE
HBL backwards-compatibility

### ISSUE THREAD

**Issue by PixelSergey** [LumaTeam/Luma3DS#860]
With luma 8.0+, it is impossible to run older/non-updated homebrew titles, as rosalina disables title selection. It is also impossible to run hblauncher_loader as rosalina takes that over. The only solution to backwards-compatibility currently is to get a legacy luma version and using hblauncher_loader or to downgrade. This is a pretty big flaw, and could be easily fixed by disabling hblauncher_loader overtaking, enabling title selection or adding an option to overtake/leave hblauncher_loader alone.
All homebrew *hax, obviously, don't work either.

**Comment by fincs** [comment]
This is intentional. It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

Also, HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature. You can also use GodMode9 instead of braindump for dumping game assets.

hax 2.x cannot run because Rosalina reorganizes system memory layout and is therefore inherently incompatible.
