### ISSUE TITLE
Feature Request: Allow removal of files via RomFS patches

### ISSUE THREAD

**Issue by mariomadproductions** [LumaTeam/Luma3DS#898]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.5.0-38E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap/Sighax

**Luma3DS version:**

8.1.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: (x)

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Feature Request: Allow "removal" of files via RomFS patches. Maybe by (re?)adding support for .romfs file or a feature that reads a text file with all the paths of files that the user wants "removed".

**Steps to reproduce:**

N/A

**Dump file:**

N/A

**Comment by ghost** [comment]
Unless your game has an internal handler for missing files or you edit its code.bin to no longer reference said files, the game would likely just crash. For this reason, I do not feel this is appropriate for Luma. 

However, please let me know if I'm misunderstanding what you're saying, because even if this were possible I don't see why packing all the files into a single file called romfs a la HANS would make this work.

**Comment by mariomadproductions** [comment]
I want to remove files because I suspect the game does have a internal handler for missing files.

I assumed that the Luma/HANS replaced the game .romfs with the sd .romfs but I guess I assumed incorrectly.

**Comment by mariomadproductions** [comment]
How is this invalid?
