### ISSUE TITLE
Can Luma3DS be provided in a .zip instead of a .7z ?

### ISSUE THREAD

**Issue by jason0597** [LumaTeam/Luma3DS#915]
Due to the size of the files, compression isn't really needed. Providing it in a .zip would simplify it for a lot of people downloading Luma3DS as they wouldn't need a 3rd party tool to extract it.

**Comment by Chriscox462** [comment]
You could always build from the .zip source code instead.Also 7 zip is not a problem as The portable Version of 7zip is only 8 MB(3 MB installer).

**Comment by urherenow** [comment]
You shouldn't get into the habit of building from .zip source code. You should always clone the repo using git. Most 3ds projects require --recursive cloning, and downloading a .zip of the repo simply won't get you there...

**Comment by fincs** [comment]
> Most 3ds projects require --recursive cloning

What

**Comment by urherenow** [comment]
like ntrboot_flasher, for instance (and numerous other projects)

If you don't "git clone --recursive https://github.com/....." you won't be able to build anything because you will be missing all of the required submodules. I understand it isn't required for Luma, I'm just saying that simply downloading a source  .zip from github is a bad habit to get into.

**Comment by ghost** [comment]
This has been requested before and may change in the future, but currently there are no plans to do so as far as I'm aware.
