### ISSUE TITLE
Can't boot Updated SysNAND O3DS since v5.3.1

### ISSUE THREAD

**Issue by thiagokokada** [LumaTeam/Luma3DS#99]
I have a O3DS with Updated SysNAND v11.0.0-33, A9LH and Luma3DS. Since version v5.3.1 my 3DS does not boot, with v5.3.1 I just got a black screen, while in v.5.5 I got stuck in boot splash.

I can boot in emuNAND (v9.2) and yeah, I used Gateway downgrader in the past. However this current version of my firmware is from a backup I made before the downgrade process, using Gateway software.

**Comment by MelonGx** [comment]
1. Dump CTRNAND with D9.
2. Mount and defrag CTRNAND on PC.
3. Restore defragged CTRNAND.

**Comment by thiagokokada** [comment]
Did it, still not working.

**Comment by thiagokokada** [comment]
Ok, feeling dumb now. After looking at [FAQ](https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting), got it working again.

Any reason that this change in 5.3.1 was necessary, though? Or is it mostly a code cleanup?

**Comment by AuroraWright** [comment]
It was because I had to choose between supporting NANDs with a partial background update (like 9.0 NANDs which had the 10.4 FIRM downloaded) and NANDs messed up by Gateway. Since the first behavior is intended and the second is a GW screwup I chose the first

**Comment by Verequies** [comment]
I have an Old 3DS XL (Toshiba NAND) which is working fine with Luma3DS v5.5 booted through Homebrew Launcher, and a Old 3DS Non-XL (Samsung NAND) booting Luma3DS using the same method. However the Old 3DS Non-XL won't boot v5.5, while it can boot v5.4 perfectly fine. Any reason why this might be?

EDIT: Figured it out, the supplied .3dsx file for Luma3DS v5.5 doesn't boot. Using one from v5.4 and then using the v5.5 Luma3DS.dat fixes the issue. Odd since it works fine on the Old 3DS XL?

**Comment by Verequies** [comment]
The last commit that works is c3ad7ed.

**Comment by timbiotic** [comment]
I am stuck, I have the issue where I cant run past 5.3.  But the FAQ files are riddled with viruses and I cannot get the files referenced. Is there a safe mirror without Trojans?

**Comment by ultra-azu** [comment]
They doesn't have trojans. Maybe your antivirus haved a false positive?

**Comment by TuxSH** [comment]
Avira Antivirus, I assume?

**Comment by ultra-azu** [comment]
Or timbiotic clicked an ad...

**Comment by ghost** [comment]
Lol

**Comment by pbanj** [comment]
That or he has something that's replacing links
